import "./global.css";
import data from "./assets/data/data";
import { staticPage } from "./app/components/StaticPage";
import { render } from "./app/components/Render";
import { selectedToys, showSelectedCount } from "./app/components/SelectedToys";
import { search, onSearchEvent } from "./app/components/Search";
import { controls } from "./app/components/Controls";
import { attributesFiltersComponent } from "./app/components/AttributesFilterComponent";
import { ranges } from "./app/components/Ranges";
import { sorting } from "./app/components/Sorting";
import { reset } from "./app/components/Reset";
import { renderToys } from "./app/components/RenderToys";
import { toysList } from "./app/components/ToysList";
import { selectedToysModal } from "./app/components/SelectedToys";

const site = document.querySelector(".app");
render(site, staticPage());
selectedToys();
search();
onSearchEvent();
showSelectedCount();
controls();
attributesFiltersComponent();
ranges();
sorting();
reset();
toysList();
renderToys(data);
selectedToysModal();
